# unset WEBOTS_HOME
# unset LD_LIBRARY_PATH
# unset JAVA_HOME
# snapcraft  # --destructive-mode may be needed if run on a virtual machine
# snap install --dangerous webots_R2023b_amd64.snap
# webots
# snap uninstall webots
# snapcraft login
# snapcraft push webots_R2023b_amd64.snap
# snap install webots

name: webots
title: Webots
base: core22
version: 'R2025a'
adopt-info: webots
summary: Webots is a free and open-source 3D robot simulator
description: |
  Webots is a free and open-source 3D robot simulator.
  It allows you to create 3D simulation models of robots interacting with their
  environment through sensors and actuators. Libraries of robots, sensors,
  actuators and objects are provided, but you can create your own. Collision
  detections, rigid body dynamics and fluid dynamics rely on a modified version
  of the ODE physics engine. The robot controller programs can be written
  outside of Webots in C, C++, Python, Java or MATLAB using a simple API.
  Webots features a 3D web interface allowing you to publish simulations online.
icon: webots.png
license: Apache-2.0
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
- build-on: [amd64]
  build-for: [amd64]
environment:
  JAVA_HOME: "$SNAP/usr/lib/jvm/java-18-openjdk-amd64"
  PATH: "$JAVA_HOME/bin:$PATH"

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgweather-4:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgweather-4
  /usr/lib/evolution-data-server:
    symlink: $SNAP/usr/lib/evolution-data-server
  /usr/bin/gnome-control-center:
    symlink: $SNAP/usr/bin/gnome-control-center
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm
  /etc/openal: # to allow openal to read its global configuration file
    bind: $SNAP/etc/openal
  /usr/include:  # to allow gcc compiler to find system include files
    bind: $SNAP/usr/include
  /usr/lib/$CRAFT_ARCH_TRIPLET/libc_nonshared.a:
    bind-file: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libc_nonshared.a
    # bind-file: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libc_nonshared.a


parts:
  webots:
    build-packages:
    - git
    - python3-pip
    plugin: make
    build-environment:
    - WEBOTS_HOME: "$SNAPCRAFT_PART_BUILD"
    - JAVA_HOME: "/usr/lib/jvm/java-18-openjdk-amd64"
    - PATH: "$JAVA_HOME/bin:$PATH"
    - PATH: /snap/gnome-42-2204-sdk/current/usr/bin${PATH:+:$PATH}
    - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/snap/gnome-42-2204-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
    - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    - PKG_CONFIG_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    - GETTEXTDATADIRS: /snap/gnome-42-2204-sdk/current/usr/share/gettext-current${GETTEXTDATADIRS:+:$GETTEXTDATADIRS}
    - GDK_PIXBUF_MODULE_FILE: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/gdk-pixbuf-current/loaders.cache
    - ACLOCAL_PATH: /snap/gnome-42-2204-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
    - PYTHONPATH: /snap/gnome-42-2204-sdk/current/usr/lib/python3.10:/snap/gnome-42-2204-sdk/current/usr/lib/python3/dist-packages:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/gobject-introspection${PYTHONPATH:+:$PYTHONPATH}
    stage:
      - -usr/lib/x86_64-linux-gnu/libGL.so.1
      - -usr/lib/x86_64-linux-gnu/libGLX.so.0
      - -usr/lib/x86_64-linux-gnu/libEGL.so.1
      - -usr/lib/x86_64-linux-gnu/dri/*
    #source: https://cyberbotics.com/files/repository/beta/webots.tar.bz2
    # When building locally, uncomment the following line:
    source-type: local
    source: webots/
    # When building from snapcraft.io, uncomment the following 4 lines:
    #source: https://github.com/cyberbotics/webots
    #source-type: git
    #source-depth: 1
    #source-branch: feature-snapcraft-build
    # We should specify either the source-branch or the source-tag, but not both
    # source-tag: R2023b
    override-pull: |
      craftctl default
      ./scripts/install/linux_optional_compilation_dependencies.sh
      sudo apt install --yes xvfb
      python3 -m pip install aqtinstall
      pip3 install distro
      sudo apt install python3-distro
    override-prime: |
      craftctl default
      rm -vf usr/lib/jvm/java-11-openjdk-*amd64/lib/security/blacklisted.certs
    stage-packages:
    - lsb-release
    - openjdk-18-jdk
    - ca-certificates-java
    - build-essential

apps:
  webots:
    extensions: [gnome]
    command: usr/share/webots/webots
    command-chain:
      - snap/command-chain/desktop-launch
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTAL: '1'
      LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      # LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu:$SNAP/lib:$SNAP/usr/lib:$LD_LIBRARY_PATH
    plugs:
      - desktop
      - gtk-3-themes
      - icon-themes
      - sound-themes
      - gnome-42-2204
      - network
      - home
      - gsettings
      - wayland
      - x11
      - audio-playback
      - browser-support
      - hidraw
      - hostname-control
      - joystick
      - unity7

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-42-2204:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-42-2204
