# unset WEBOTS_HOME
# unset LD_LIBRARY_PATH
# unset JAVA_HOME
# snapcraft  # --destructive-mode may be needed if run on a virtual machine
# snap install --dangerous webots_R2020b-rev2_amd64.snap
# webots
# snap uninstall webots
# snapcraft login
# snapcraft push webots_R2020b-rev2_amd64.snap
# snap install webots

name: webots
title: Webots
base: core18
version: 'R2020b-rev2'
summary: Webots is a free and open-source 3D robot simulator
description: |
  Webots is a free and open-source 3D robot simulator.
  It allows you to create 3D simulation models of robots interacting with their
  environment through sensors and actuators. Libraries of robots, sensors,
  actuators and objects are provided, but you can create your own. Collision
  detections, rigid body dynamics and fluid dynamics rely on a modified version
  of the ODE physics engine. The robot controller programs can be written
  outside of Webots in C, C++, Python, ROS, Java or MATLAB using a simple API.
  Webots features a 3D web interface allowing you to publish simulations online.
icon: webots.png
license: Apache-2.0
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
architectures:
- build-on: amd64
  run-on: amd64
environment:
  JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
  PATH: "$JAVA_HOME/bin:$PATH"

layout:
  /etc/openal: # to allow openal to read its global configuration file
    bind: $SNAP/etc/openal
  /usr/include:  # to allow gcc compiler to find system include files
    bind: $SNAP/usr/include
  /usr/lib/x86_64-linux-gnu:  # to allow gcc linker to find the necessary libraries
    bind: $SNAP/usr/lib/x86_64-linux-gnu
  /usr/share/libdrm:  # to fix a warning displayed by Webots on AMD GPUs
    bind: $SNAP/usr/share/libdrm

parts:
  desktop-gtk3:
    build-packages:
    - build-essential
    - libgtk-3-dev
    make-parameters:
    - FLAVOR=gtk3
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    stage-packages:
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libgtk-3-0
    - libgdk-pixbuf2.0-0
    - libglib2.0-bin
    - libgtk2.0-0
    - libgtk-3-bin
    - unity-gtk3-module
    - libappindicator3-1
    - xdg-user-dirs
    - ibus-gtk3
    - libibus-1.0-5
    - fcitx-frontend-gtk3

  webots:
    build-packages:
    - git
    - python-pip
    plugin: make
    build-environment:
    - WEBOTS_HOME: "$SNAPCRAFT_PART_BUILD"
    - ROS_DISTRO: "melodic"
    #source: https://cyberbotics.com/files/repository/beta/webots.tar.bz2
    # When building locally, uncomment the following line:
    source-type: local
    source: webots/
    # When building from snapcraft.io, uncomment the following 4 lines:
    #source: https://github.com/cyberbotics/webots
    #source-type: git
    #source-depth: 1
    #source-branch: feature-snapcraft-build
    # We should specify either the source-branch or the source-tag, but not both
    # source-tag: R2019b
    override-pull: |
      snapcraftctl pull
      ./scripts/install/linux_optional_compilation_dependencies.sh
      sudo apt install xvfb
      Xvfb :99 &
      export DISPLAY=:99
    stage-packages:
    - openjdk-11-jdk
    - ca-certificates-java
    - build-essential
    - libc6-dev
    - ffmpeg
    - freeglut3-dev
    - libasn1-8-heimdal
    - libasound2
    - libatk1.0-0
    - libavutil55
    - libblkid1
    - libcanberra-gtk-module
    - libcanberra-gtk3-module
    - libcrystalhd3
    - libcurl3-gnutls
    - libdbus-1-3
    - libdouble-conversion1
    - libdrm-common
    - libfreeimage3
    - libfreetype6
    - libgcc1
    - libgcrypt20
    - libgd3
    - libgeos-dev
    - libgfortran4
    - libglib2.0-0
    - libgl1
    - libglu1-mesa
    - libglvnd0
    - libglx0
    - libgpg-error0
    - libgsm1
    - libgssapi3-heimdal
    - libssh-4
    - libgtk-3-0
    - libhcrypto4-heimdal
    - libheimbase1-heimdal
    - libheimntlm0-heimdal
    - libhx509-5-heimdal
    - libjpeg8-dev
    - libkrb5-26-heimdal
    - libldap-2.4-2
    - libltdl7
    - liblzma5
    - libminizip1
    - libmount1
    - libmp3lame0
    - libnghttp2-14
    - libnss3
    - libnuma1
    - libopenal-data
    - libopencore-amrnb0
    - libopencore-amrwb0
    - libopus0
    - libpcre3
    - libproj12
    - libpsl5
    - libpulse-mainloop-glib0
    - libroken18-heimdal
    - librtmp1
    - libsasl2-2
    - libselinux1
    - libshine3
    - libslang2
    - libsnappy1v5
    - libsndio6.1
    - libsoxr0
    - libspeex1
    - libssh-dev
    - libssh-gcrypt-4
    - libssl1.1
    - libstdc++6
    - libswresample2
    - libsystemd0
    - libtheora0
    - libtinfo5
    - libtwolame0
    - libudev1
    - libuuid1
    - libva2
    - libva-drm2
    - libva-x11-2
    - libvdpau1
    - libvo-amrwbenc0
    - libwavpack1
    - libwind0-heimdal
    - libx11-data
    - libx11-xcb1
    - libx265-146
    - libxaw7
    - libxcb-glx0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-randr0
    - libxcb-render-util0
    - libxcb-shape0
    - libxcb-sync1
    - libxcb-util1
    - libxcb-xfixes0
    - libxcb-xinerama0
    - libxcb-xkb1
    - libxft2
    - libxkbcommon-x11-0
    - libxrandr2
    - libxrender1
    - libxslt1.1
    - libxss1
    - libxtst6
    - libxvidcore4
    - liblz4-1
    - libzip-dev
    - libzvbi0
    - libzzip-0-13
    - locales-all
    - lsb-release
    - util-linux
    - zlib1g

apps:
  webots:
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      DISABLE_WAYLAND: 1
    plugs:
    - audio-playback
    - browser-support
    - desktop
    - desktop-legacy
    - gsettings
    - hidraw
    - home
    - hostname-control
    - joystick
    - network
    - opengl
    - pulseaudio
    - wayland
    - unity7
    - x11
    desktop: usr/share/webots/resources/webots.desktop
    command: desktop-launch $SNAP/usr/share/webots/webots
