name: Webots Snap Package Creation
on: 
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  schedule:
  - cron: "0 23 * * *"
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

jobs:
  cleanup-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  build:
    needs: cleanup-runs
    if: ${{ github.event_name == 'schedule' || github.event_name == 'push' || contains(github.event.pull_request.labels.*.name, 'test creation') }}
    strategy:
      matrix:
        branch: [master]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone Webots Repository
      run: |
        sudo apt install git
        git clone --recurse-submodules --depth 3 --single-branch --branch ${{ matrix.branch }} https://github.com/cyberbotics/webots.git
    - name: Set Commit SHA in Version
      if: ${{ github.event_name == 'schedule' }}
      run: python scripts/packaging/set_commit_and_date_in_version.py ${{ github.sha }}
    - name: Setup Xvfb
      run: |
        Xvfb :99 &
        export DISPLAY=:
    - name: Create Snap Package
      uses: snapcore/action-build@v1
      id: snapcraft
    - name: Upload Snap Package
      uses: actions/upload-artifact@v2
      with:
        name: 'snap'
        path: ${{ steps.snapcraft.outputs.snap}}
    - name: Copy Snap Package in webots/distribution
      run: cp ${{ steps.snapcraft.outputs.snap}} webots/distribution
    - name: Create/Update GitHub Release
      if: ${{ github.event_name == 'schedule' || github.event_name == 'push'}}
      run: |
        sudo python -m pip install requests PyGithub
        webots/scripts/packaging/publish_release.py --key=${{ secrets.GITHUB_TOKEN }} --repo=${{ github.repository }} --branch=${{ github.ref }} --commit=${{ github.sha }} --tag=${{ github.ref }}
